version: "3"

services:
    postgres:
        container_name: postgres
        restart: always
        build: ./postgres
        env_file:
            - .env
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        ports:
            - "5432:5432"

    web:
        container_name: blog
        restart: always
        build: ./blog
        expose:
            - "8000"
        volumes:
            - ./blog:/blog
            - static_volume:/vol/web/static
        env_file:
            - .env
        environment:
            - POSTGRES_HOST=${POSTGRES_HOST}
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        links:
            - postgres:postgres
        depends_on:
            - postgres
            
    nginx:
        container_name: nginx
        restart: always
        build: ./nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - static_volume:/static
        volumes_from:
            - web
        links:
            - web:web
        depends_on:
            - web
    

volumes:
    static_volume:
