version: "3.9"
services:
    postgres:
        container_name: postgres
        restart: always
        build: ./postgresql
        image: ghcr.io/kh-elbrus/ci-cd-django-web-app/postgres
        labels:
            - name=postgres
        env_file:
            - .env
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        ports:
            - "5432:5432"
        volumes:
          - postgres_data:/var/lib/postgresql/data/
    web:
        container_name: blog
        restart: always
        build: ./blog
        image: ghcr.io/kh-elbrus/ci-cd-django-web-app/blog
        expose:
            - "8000"
        volumes:
            - ./blog:/blog
            - static_volume:/vol/web/static
        env_file:
            - .env
        environment:
            - POSTGRES_HOST=${POSTGRES_HOST}
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        links:
            - postgres:postgres
        depends_on:
            - postgres
        command: >
            sh -c "bash ./migrate.sh && 
                   bash ./entrypoint.sh"
    nginx:
        container_name: nginx
        restart: always
        build: ./nginx
        image: ghcr.io/kh-elbrus/ci-cd-django-web-app/nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - static_volume:/static
        volumes_from:
            - web
        links:
            - web:web
        depends_on:
            - web
volumes:
    static_volume:
    postgres_data:
