name: Build & Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  Build-Test-Web-Application:

    runs-on: ubuntu-latest
    env:
      DOT_ENV_FILE: ${{ secrets.DOT_ENV_FILE }}

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image  
      run: |
        export IMG_VERSION=$(git log -1 --pretty=%h)
        echo $DOT_ENV_FILE | base64 --decode > .env
        docker-compose -f docker-compose-dev.yml build
    
    - name: Run docker containers
      run: docker-compose -f docker-compose-dev.yml up -d
      
    - name: Check running docker containers
      run: docker ps 
      
    - name: Run django tests
      run: docker exec -i blog python manage.py test
